name: Create a test pull request
on:
  workflow_dispatch:
    inputs:
      api_shortname:
        required: true
        type: string
        description: "`api_shortname`: Name for the new directory name and (default) artifact name"
jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo  "api_shortname: ${{ github.event.inputs.api_shortname }}" > hello.txt
      - run: |

          set -eo pipefail
          set -x
          git checkout -b test-pull-request-branch
          [ -z "`git config user.email`" ] && git config --global user.email "${USERNAME:-script}@google.com"
          [ -z "`git config user.name`" ] && git config --global user.name "${USERNAME:-script}"
          git add hello.txt
          git commit -a -m "added hello.txt from GitHub Actions"
          git push --set-upstream origin "${{ github.run_id }}-${{ github.run_attempt }}"
          gh pr create --title "Pull request from GitHub Actions" --body "This is test." \
              --head "${{ github.run_id }}-${{ github.run_attempt }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
